package payloadpolicy

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	disallowedKeys = map[string]string{
		"access_token":     "tokens are not accepted in job payloads",
		"api_key":          "API keys are not accepted in job payloads",
		"apikey":           "API keys are not accepted in job payloads",
		"auth_token":       "tokens are not accepted in job payloads",
		"authorization":    "authorization material is not accepted in job payloads",
		"bearer":           "bearer tokens are not accepted in job payloads",
		"captcha_response": "CAPTCHA-solving material is not accepted in job payloads",
		"captcha_solution": "CAPTCHA-solving material is not accepted in job payloads",
		"captcha_token":    "CAPTCHA-solving material is not accepted in job payloads",
		"cookie":           "cookies are not accepted in job payloads",
		"cookies":          "cookies are not accepted in job payloads",
		"credential":       "credentials are not accepted in job payloads",
		"credentials":      "credentials are not accepted in job payloads",
		"id_token":         "tokens are not accepted in job payloads",
		"mfa_code":         "MFA codes are not accepted in job payloads",
		"novnc_url":        "noVNC URLs must be generated by the runtime",
		"password":         "passwords are not accepted in job payloads",
		"private_key":      "private keys are not accepted in job payloads",
		"refresh_token":    "tokens are not accepted in job payloads",
		"secret":           "secrets are not accepted in job payloads",
		"session":          "browser session material is not accepted in job payloads",
		"session_cookie":   "cookies are not accepted in job payloads",
		"session_state":    "browser session state is not accepted in job payloads",
		"set_cookie":       "cookies are not accepted in job payloads",
		"storage_state":    "browser storage state is not accepted in job payloads",
		"totp":             "TOTP codes are not accepted in job payloads",
		"x_api_key":        "API keys are not accepted in job payloads",
	}
	bearerValuePattern     = regexp.MustCompile(`(?i)\bbearer\s+[A-Za-z0-9._~+/=-]{12,}`)
	privateKeyValuePattern = regexp.MustCompile(`(?is)-----BEGIN [A-Z ]*PRIVATE KEY-----`)
	captchaSolverPattern   = regexp.MustCompile(`(?i)\b(solve|bypass|delegate|outsource)\b.{0,40}\bcaptcha\b|\bcaptcha\b.{0,40}\b(solver|solving|bypass)\b`)
)

type Violation struct {
	Path   string
	Reason string
}

func (v Violation) Error() string {
	if v.Path == "" {
		return v.Reason
	}
	return fmt.Sprintf("%s at %s", v.Reason, v.Path)
}

func Validate(value any) error {
	return validateValue(value, "$")
}

func validateValue(value any, path string) error {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			childPath := path + "." + key
			normalized := NormalizeKey(key)
			if reason, found := disallowedKeyReason(normalized); found {
				return Violation{Path: childPath, Reason: reason}
			}
			if err := validateValue(child, childPath); err != nil {
				return err
			}
		}
	case []any:
		for index, child := range typed {
			if err := validateValue(child, fmt.Sprintf("%s[%d]", path, index)); err != nil {
				return err
			}
		}
	case string:
		if privateKeyValuePattern.MatchString(typed) {
			return Violation{Path: path, Reason: "private keys are not accepted in job payloads"}
		}
		if bearerValuePattern.MatchString(typed) {
			return Violation{Path: path, Reason: "bearer tokens are not accepted in job payloads"}
		}
		if captchaSolverPattern.MatchString(typed) {
			return Violation{Path: path, Reason: "CAPTCHA-solving instructions are not accepted in job payloads"}
		}
	}
	return nil
}

func NormalizeKey(value string) string {
	value = regexp.MustCompile(`([a-z0-9])([A-Z])`).ReplaceAllString(strings.TrimSpace(value), `${1}_${2}`)
	value = regexp.MustCompile(`[^A-Za-z0-9]+`).ReplaceAllString(value, "_")
	value = regexp.MustCompile(`_+`).ReplaceAllString(value, "_")
	return strings.ToLower(strings.Trim(value, "_"))
}

func disallowedKeyReason(normalized string) (string, bool) {
	if normalized == "manual_session" || normalized == "session_id" {
		return "", false
	}
	if isSecretReferenceKey(normalized) {
		return "", false
	}
	if reason, found := disallowedKeys[normalized]; found {
		return reason, true
	}

	segments := strings.Split(normalized, "_")
	for _, segment := range segments {
		switch segment {
		case "password":
			return "passwords are not accepted in job payloads", true
		case "secret":
			return "secrets are not accepted in job payloads", true
		case "token":
			return "tokens are not accepted in job payloads", true
		case "credential", "credentials":
			return "credentials are not accepted in job payloads", true
		case "cookie", "cookies":
			return "cookies are not accepted in job payloads", true
		case "captcha":
			return "CAPTCHA-solving material is not accepted in job payloads", true
		case "totp":
			return "TOTP codes are not accepted in job payloads", true
		case "mfa":
			return "MFA codes are not accepted in job payloads", true
		case "authorization", "bearer":
			return "authorization material is not accepted in job payloads", true
		}
	}

	compact := strings.ReplaceAll(normalized, "_", "")
	for _, marker := range []struct {
		value  string
		reason string
	}{
		{"apikey", "API keys are not accepted in job payloads"},
		{"privatekey", "private keys are not accepted in job payloads"},
		{"storagestate", "browser storage state is not accepted in job payloads"},
		{"sessionstate", "browser session state is not accepted in job payloads"},
		{"sessiontoken", "tokens are not accepted in job payloads"},
		{"accesskey", "API keys are not accepted in job payloads"},
	} {
		if strings.Contains(compact, marker.value) {
			return marker.reason, true
		}
	}
	return "", false
}

func isSecretReferenceKey(normalized string) bool {
	return normalized == "secret_id" ||
		normalized == "secret_ref" ||
		strings.HasSuffix(normalized, "_secret_id") ||
		strings.HasSuffix(normalized, "_secret_ref")
}
