{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubag.fullname" . }}-secrets
  labels:
    {{- include "ubag.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key := (list "UBAG_APP_SECRET" "UBAG_POSTGRES_DSN" "UBAG_MINIO_ACCESS_KEY" "UBAG_MINIO_SECRET_KEY" "UBAG_WEBHOOK_SECRET") }}
  {{- $value := index $.Values.secrets $key }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
