<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { api, listOf } from '$lib/api/client';
  import { EM_DASH, fmtCount, fmtTime, humanize, loadFleetNodes, readinessLines } from '$lib/api/fleet';
  import ErrorPanel from '$lib/components/ErrorPanel.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import DeniedPanel from '$lib/components/DeniedPanel.svelte';
  import StatusBadge from '$lib/components/StatusBadge.svelte';
  import LiveBrowser from '$lib/components/LiveBrowser.svelte';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import SkeletonCards from '$lib/components/SkeletonCards.svelte';
  import UpdatedAgo from '$lib/components/UpdatedAgo.svelte';
  import { pollWhileVisible } from '$lib/poll';
  import type {
    BrowserInstance,
    BrowserContext,
    BrowserTab,
    BrowserSummary,
    ConcurrencyView,
    FleetNode,
  } from '$lib/api/types';

  let summary = $state<BrowserSummary | null>(null);
  let instances = $state<BrowserInstance[]>([]);
  let contexts = $state<BrowserContext[]>([]);
  let tabs = $state<BrowserTab[]>([]);

  let loading = $state(true);
  let denied = $state(false);
  let error = $state<string | null>(null);
  let lastUpdated = $state<Date | null>(null);

  let selectedInstance = $state<BrowserInstance | null>(null);

  let terminalEl = $state<HTMLElement | null>(null);
  let term: { writeln: (s: string) => void; dispose: () => void } | null = null;
  let termReady = $state(false);
  let terminalInstanceId = $state<string | null>(null);

  let instanceContexts = $derived(
    selectedInstance
      ? contexts.filter((c) => c.instance_id === instanceId(selectedInstance!))
      : []
  );

  let instanceTabs = $derived(
    selectedInstance
      ? tabs.filter((t) => instanceContexts.some((c) => contextId(c) === t.context_id))
      : []
  );

  // noVNC URLs must be runtime-generated by the gateway/worker and loopback-scoped.
  let noVncSrc = $derived.by(() => {
    const value = selectedInstance?.novnc_url;
    return isLoopbackHttpUrl(value) ? value! : null;
  });

  let rejectedNoVnc = $derived(Boolean(selectedInstance?.novnc_url && !noVncSrc));

  // --- Adaptive concurrency ceilings (GET /v1/concurrency, concurrency:read) ---
  let concurrency = $state<ConcurrencyView[]>([]);
  let concurrencyDenied = $state(false);
  let concurrencyUnavailable = $state(false);

  async function loadConcurrency() {
    concurrencyDenied = false;
    concurrencyUnavailable = false;
    const res = await api.get<{ kind?: string; data?: ConcurrencyView[] }>('/v1/concurrency');
    if (res.denied) { concurrencyDenied = true; return; }
    if (res.status === 501 || res.status === 404) { concurrencyUnavailable = true; return; }
    if (res.error) { concurrencyUnavailable = true; return; }
    concurrency = res.data?.data ?? [];
  }

  // --- Placement across helper nodes (GET /v1/fleet/nodes, fleet:read) ---
  // Null (section hidden) unless the gateway answers 200; 501/404/403 all read as "not available".
  let fleetNodes = $state<FleetNode[] | null>(null);

  async function loadFleet(force = false) {
    fleetNodes = await loadFleetNodes(force);
  }

  async function load(silent = false) {
    if (!silent) {
      loading = true;
      error = null;
      denied = false;
    }

    const [sumRes, instRes, ctxRes, tabRes] = await Promise.all([
      api.get('/v1/browser/summary'),
      api.get('/v1/browser/instances'),
      api.get('/v1/browser/contexts'),
      api.get('/v1/browser/tabs'),
    ]);

    if (instRes.denied) { denied = true; return instRes; }
    if (instRes.error) { error = instRes.error; return instRes; }
    if (!silent) loading = false;

    summary = (sumRes.data as BrowserSummary | null) ?? null;
    instances = listOf<BrowserInstance>(instRes);
    contexts = listOf<BrowserContext>(ctxRes);
    tabs = listOf<BrowserTab>(tabRes);
    selectedInstance =
      instances.find((inst) => selectedInstance && instanceId(inst) === instanceId(selectedInstance)) ??
      instances[0] ??
      null;
    lastUpdated = new Date();
  }

  async function initTerminal() {
    if (!terminalEl || termReady) return;
    try {
      const { Terminal } = await import('@xterm/xterm');
      await import('@xterm/xterm/css/xterm.css');
      term = new Terminal({
        // Terminal panes render on canvas where CSS vars don't resolve; use the
        // ink token's concrete value (oklch 20% 0.022 55) for the background.
        theme: { background: '#221e1b', foreground: '#f4f1ec' },
        fontFamily: '"Cascadia Mono", "Fira Code", monospace',
        fontSize: 12,
        rows: 20,
        cursorBlink: true,
        scrollback: 200,
      });
      (term as unknown as { open: (el: HTMLElement) => void }).open(terminalEl);
      fitTerm();
      termReady = true;
      refreshTerminal();
    } catch (e) {
      console.warn('xterm init failed', e);
    }
  }

  // Keep the terminal width matched to its container without the FitAddon
  // dependency: resize against a measured monospace advance (~0.6em at 12px).
  function fitTerm() {
    if (!term || !terminalEl) return;
    const width = terminalEl.clientWidth;
    if (width < 80) return;
    const cols = Math.max(20, Math.floor((width - 24) / 7.2));
    (term as unknown as { resize?: (cols: number, rows: number) => void }).resize?.(cols, 20);
  }

  function writeWelcome() {
    if (!term) return;
    term.writeln('UBAG Browser Session Log');
    term.writeln('--------------------------------------------------------------------------------');
    if (selectedInstance) {
      term.writeln(`Instance:  ${instanceId(selectedInstance)}`);
      term.writeln(`Status:    ${instanceState(selectedInstance)}`);
      term.writeln(`Contexts:  ${selectedInstance.context_count ?? 0}`);
      term.writeln('--------------------------------------------------------------------------------');
      term.writeln('Live log streaming requires a direct WebSocket connection to the gateway.');
      term.writeln('Use the gateway browser stream endpoint for this instance.');
    } else {
      term.writeln('Select an instance row to view its log stream.');
    }
  }

  function refreshTerminal() {
    if (!term) return;
    const reset = (term as unknown as { reset?: () => void }).reset;
    if (reset) {
      reset.call(term);
    } else {
      (term as unknown as { clear?: () => void }).clear?.();
    }
    writeWelcome();
    terminalInstanceId = selectedInstance ? instanceId(selectedInstance) : null;
  }

  function selectInstance(inst: BrowserInstance) {
    selectedInstance = inst;
    if (termReady) refreshTerminal();
  }

  function instanceId(inst: BrowserInstance): string {
    return inst.instance_id;
  }

  function instanceState(inst: BrowserInstance): string {
    return inst.state ?? 'unknown';
  }

  function contextId(ctx: BrowserContext): string {
    return ctx.context_id;
  }

  function tabId(tab: BrowserTab): string {
    return tab.tab_id;
  }

  function tabState(tab: BrowserTab): string {
    return tab.state ?? 'unknown';
  }

  function tabConversation(tab: BrowserTab): string {
    return tab.conversation_id ?? '';
  }

  function contextTabCount(ctx: BrowserContext): number {
    return tabs.filter((tab) => tab.context_id === contextId(ctx)).length;
  }

  function isLoopbackHttpUrl(value?: string | null): boolean {
    if (!value) return false;
    try {
      const url = new URL(value);
      const host = url.hostname.toLowerCase();
      return (
        url.protocol === 'http:' &&
        (host === 'localhost' || host === '127.0.0.1' || host.startsWith('127.') || host === '[::1]' || host === '::1')
      );
    } catch {
      return false;
    }
  }

  function truncate(s: string | undefined | null, n: number): string {
    if (!s) return '-';
    return s.length > n ? s.slice(0, n) + '...' : s;
  }

  onMount(() => {
    load();
    loadConcurrency();
    loadFleet();
    const stopPolling = pollWhileVisible(
      () => {
        void loadFleet();
        return load(true);
      },
      45_000,
      { immediate: false },
    );
    // Refit the terminal when the viewport changes.
    const onResize = () => fitTerm();
    window.addEventListener('resize', onResize);
    return () => {
      stopPolling();
      window.removeEventListener('resize', onResize);
    };
  });

  $effect(() => {
    if (terminalEl && !termReady) {
      initTerminal();
    }
  });

  $effect(() => {
    const currentInstanceId = selectedInstance ? instanceId(selectedInstance) : null;
    if (termReady && currentInstanceId !== terminalInstanceId) {
      refreshTerminal();
    }
  });

  onDestroy(() => {
    term?.dispose();
  });
</script>

<div class="space-y-6">
  <PageHeader title="Browser Sessions" subtitle="Live Chromium automation via UBAG gateway.">
    {#snippet actions()}
      <UpdatedAgo at={lastUpdated} />
      <button onclick={() => load()} class="btn btn-secondary btn-sm">Refresh</button>
    {/snippet}
  </PageHeader>

  {#if loading}
    <SkeletonCards count={3} cols="grid-cols-1 sm:grid-cols-3" />
  {:else if denied}
    <DeniedPanel resource="browser sessions" />
  {:else if error}
    <ErrorPanel message={error} retry={load} />
  {:else}
    {#if summary}
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
        {#each [
          { label: 'Instances', value: summary.total_instances ?? 0, color: 'text-marine' },
          { label: 'Contexts', value: summary.total_contexts ?? 0, color: 'text-accent-deep' },
          { label: 'Tabs', value: summary.total_tabs ?? 0, color: 'text-success' },
        ] as card (card.label)}
          <div class="card flex flex-col gap-1">
            <span class="text-xs text-ink-mute uppercase tracking-wider font-mono">{card.label}</span>
            <span class="text-2xl font-display font-bold {card.color}">{card.value}</span>
          </div>
        {/each}
      </div>
    {/if}

    <!-- Placement: which helper nodes take new work, and why not. Hidden unless the fleet endpoint answers 200. -->
    {#if fleetNodes}
      <section class="space-y-2" aria-labelledby="placement-heading">
        <div class="flex items-center justify-between">
          <h2 id="placement-heading" class="text-sm font-semibold text-ink uppercase tracking-wider">Placement</h2>
          <button onclick={() => loadFleet(true)} class="text-xs text-accent-deep hover:underline">Refresh</button>
        </div>
        {#if fleetNodes.length === 0}
          <EmptyState message="No helper nodes." hint="Nodes appear once the fleet manager grants this gateway capacity." />
        {:else}
          <!-- Seven columns can overflow on a narrow screen: keep the scroll area keyboard-reachable. -->
          <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
          <div class="table-wrap" role="region" aria-label="Helper node placement" tabindex="0">
            <table class="w-full text-xs">
              <thead class="thead">
                <tr>
                  <th class="th">Node</th>
                  <th class="th">Region</th>
                  <th class="th">State</th>
                  <th class="th">Heartbeat</th>
                  <th class="th">Slots</th>
                  <th class="th">Pressure</th>
                  <th class="th">Provider sessions</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each fleetNodes as node (node.node_id)}
                  {@const sessions = readinessLines(node)}
                  <tr class="transition-colors hover:bg-paper-soft/70">
                    <td class="td font-mono text-ink" title={node.node_id}>{node.label}</td>
                    <td class="td font-mono">{node.region || EM_DASH}</td>
                    <td class="td">
                      <div class="flex flex-wrap items-center gap-2">
                        <StatusBadge status={node.state} />
                        {#if node.ineligible_reason}
                          <span class="text-ink-mute">{humanize(node.ineligible_reason)}</span>
                        {/if}
                      </div>
                    </td>
                    <td class="td whitespace-nowrap">{fmtTime(node.heartbeat_at)}</td>
                    <td class="td whitespace-nowrap">{fmtCount(node.usage.workloads_in_use)} / {fmtCount(node.usage.admission_limit)}</td>
                    <td class="td">
                      {#if node.pressure.admission_reduced}
                        <span class="text-warning">Reduced</span>{node.pressure.recover_at ? ` until ${fmtTime(node.pressure.recover_at)}` : ''}
                      {:else if node.pressure.admission_reduced === false}
                        Normal
                      {:else}
                        {EM_DASH}
                      {/if}
                    </td>
                    <td class="td">
                      {#each sessions as line, i (i)}
                        <p class="font-mono">{line}</p>
                      {:else}
                        {EM_DASH}
                      {/each}
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}
      </section>
    {/if}

    <!-- Live interactive browser: stream the real Chrome into the dashboard and
         drive it (log into providers) without a separate window. -->
    <div class="space-y-2">
      <div class="flex items-center justify-between">
        <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Live Browser</h2>
        <span class="text-xs text-ink-mute">Log into a provider here; the session is remembered.</span>
      </div>
      <LiveBrowser />
    </div>

    <div class="grid grid-cols-1 xl:grid-cols-2 gap-6">
      <div class="space-y-3">
        <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Instances</h2>
        {#if instances.length === 0}
          <EmptyState message="No browser instances." hint="Start a browser session via the gateway." />
        {:else}
          <div class="table-wrap">
            <table class="w-full text-sm">
              <thead class="thead">
                <tr>
                  <th class="th">Instance ID</th>
                  <th class="th">Status</th>
                  <th class="th">Contexts</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each instances as inst, i (instanceId(inst) || i)}
                  <tr
                    tabindex="0"
                    role="button"
                    aria-label="Select instance {instanceId(inst)}"
                    aria-pressed={selectedInstance ? instanceId(selectedInstance) === instanceId(inst) : false}
                    class="cursor-pointer transition-colors hover:bg-paper-soft/70"
                    class:bg-accent-soft={selectedInstance ? instanceId(selectedInstance) === instanceId(inst) : false}
                    onclick={() => selectInstance(inst)}
                    onkeydown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault();
                        selectInstance(inst);
                      }
                    }}
                  >
                    <td class="td font-mono text-xs text-ink-mute">{truncate(instanceId(inst), 12)}</td>
                    <td class="td"><StatusBadge status={instanceState(inst)} /></td>
                    <td class="td text-center">{inst.context_count ?? 0}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if contexts.length > 0}
          <h2 class="text-sm font-semibold text-ink uppercase tracking-wider pt-2">Contexts</h2>
          <div class="table-wrap">
            <table class="w-full text-sm">
              <thead class="thead">
                <tr>
                  <th class="th">Context ID</th>
                  <th class="th">Target</th>
                  <th class="th">Identity</th>
                  <th class="th">Tabs</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each contexts as ctx, i (contextId(ctx) || i)}
                  <tr class="transition-colors hover:bg-paper-soft/70">
                    <td class="td font-mono text-xs text-ink-mute">{truncate(contextId(ctx), 12)}</td>
                    <td class="td font-mono text-xs">{truncate(ctx.target_id, 16)}</td>
                    <td class="td font-mono text-xs">{truncate(ctx.identity_ref, 16)}</td>
                    <td class="td text-center">{contextTabCount(ctx)}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if tabs.length > 0}
          <h2 class="text-sm font-semibold text-ink uppercase tracking-wider pt-2">Tabs</h2>
          <div class="table-wrap">
            <table class="w-full text-sm">
              <thead class="thead">
                <tr>
                  <th class="th">Tab ID</th>
                  <th class="th">Context</th>
                  <th class="th">Conversation</th>
                  <th class="th">Current job</th>
                  <th class="th">Status</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each tabs as tab, i (tabId(tab) || i)}
                  <tr class="transition-colors hover:bg-paper-soft/70">
                    <td class="td font-mono text-xs text-ink-mute">{truncate(tabId(tab), 8)}</td>
                    <td class="td font-mono text-xs text-ink-mute">{truncate(tab.context_id, 8)}</td>
                    <td class="td text-xs max-w-[12rem] truncate" title={tabConversation(tab)}>{truncate(tabConversation(tab), 40)}</td>
                    <td class="td font-mono text-xs text-ink-mute">{truncate(tab.current_job_id, 16)}</td>
                    <td class="td"><StatusBadge status={tabState(tab)} /></td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if instances.length === 0 && contexts.length === 0 && tabs.length === 0}
          <EmptyState message="No browser sessions active." hint="Browser instances, contexts, and tabs will appear here." />
        {/if}

        <!-- Adaptive concurrency ceilings -->
        <section aria-labelledby="concurrency-heading" class="pt-2">
          <div class="flex items-center justify-between">
            <h2 id="concurrency-heading" class="text-sm font-semibold text-ink uppercase tracking-wider">Concurrency Ceilings</h2>
            {#if !concurrencyDenied && !concurrencyUnavailable}
              <button onclick={() => loadConcurrency()} class="text-xs text-accent-deep hover:underline">Refresh</button>
            {/if}
          </div>
          {#if concurrencyDenied}
            <p class="text-xs text-ink-mute mt-2 italic">Concurrency observability requires the <code class="font-mono">concurrency:read</code> permission.</p>
          {:else if concurrencyUnavailable}
            <p class="text-xs text-ink-mute mt-2 italic">Worker-reported adaptive concurrency is not available on this deployment.</p>
          {:else if concurrency.length === 0}
            <p class="text-xs text-ink-mute mt-2 italic">No worker-reported ceilings yet — they appear once a live worker runs with orchestration enabled.</p>
          {:else}
            <div class="mt-2 table-wrap">
              <table class="w-full text-xs">
                <thead class="thead">
                  <tr>
                    <th class="th">Target</th>
                    <th class="th">Identity</th>
                    <th class="th">Cap</th>
                    <th class="th">In&nbsp;Flight</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-rule">
                  {#each concurrency as c, i (i)}
                    <tr class="transition-colors hover:bg-paper-soft/70">
                      <td class="td font-mono text-ink">{c.target}</td>
                      <td class="td font-mono">{c.identity_ref}</td>
                      <td class="td text-ink" title="min {c.min}">{c.current_cap} / {c.max}</td>
                      <td class="td">{c.in_flight}</td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            </div>
          {/if}
        </section>
      </div>

      <div class="space-y-4">
        {#if selectedInstance}
          <div class="flex items-center justify-between">
            <div>
              <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Session Viewer</h2>
              <p class="text-xs font-mono text-ink-mute mt-0.5">{instanceId(selectedInstance)}</p>
            </div>
            <StatusBadge status={instanceState(selectedInstance)} />
          </div>

          <div class="space-y-1.5">
            <div class="flex items-center justify-between">
              <span class="text-xs font-mono text-ink-mute uppercase tracking-wider">Log Stream</span>
              <span class="text-xs text-ink-mute italic">WebSocket connection required for live data</span>
            </div>
            <div
              bind:this={terminalEl}
              class="w-full min-h-[180px] rounded-md overflow-hidden border border-rule bg-[#221e1b]"
              aria-label="Terminal log pane for instance {instanceId(selectedInstance)}"
            ></div>
          </div>

          {#if instanceContexts.length > 0}
            <div class="rounded-md border border-rule bg-paper-soft px-4 py-3 text-xs space-y-1">
              <p class="font-mono text-ink-mute uppercase tracking-wider mb-2">Instance Contexts</p>
              {#each instanceContexts as ctx}
                <div class="flex items-center gap-4">
                  <span class="font-mono text-ink">{truncate(contextId(ctx), 12)}</span>
                  <span class="text-ink-mute">{contextTabCount(ctx)} tab{contextTabCount(ctx) !== 1 ? 's' : ''}</span>
                </div>
              {/each}
            </div>
          {/if}

          {#if instanceTabs.length > 0}
            <div class="rounded-md border border-rule bg-paper-soft px-4 py-3 text-xs space-y-1">
              <p class="font-mono text-ink-mute uppercase tracking-wider mb-2">Instance Tabs</p>
              {#each instanceTabs as tab}
                <div class="flex items-center gap-3">
                  <span class="font-mono text-ink-mute">{truncate(tabId(tab), 8)}</span>
                  <span class="text-ink truncate max-w-[20rem]" title={tabConversation(tab)}>{truncate(tabConversation(tab), 50)}</span>
                  <StatusBadge status={tabState(tab)} />
                </div>
              {/each}
            </div>
          {/if}

          <div class="space-y-1.5">
            <div class="flex items-center justify-between">
              <span class="text-xs font-mono text-ink-mute uppercase tracking-wider">noVNC Viewer</span>
              <span class="text-xs text-ink-mute italic">Requires a runtime-generated loopback URL</span>
            </div>
            {#if noVncSrc}
              <iframe
                src={noVncSrc}
                class="w-full h-80 rounded-md border border-rule bg-paper-warm"
                title="noVNC Viewer - {instanceId(selectedInstance)}"
                sandbox="allow-same-origin allow-scripts allow-forms"
                aria-label="noVNC remote desktop viewer for instance {instanceId(selectedInstance)}"
              ></iframe>
            {:else}
              <div class="flex items-center justify-center h-80 rounded-md border border-rule bg-paper-warm">
                <div class="text-center text-xs text-ink-mute space-y-1">
                  <p class="font-medium text-ink">noVNC unavailable</p>
                  {#if rejectedNoVnc}
                    <p>The gateway returned a non-loopback noVNC URL, so it was not embedded.</p>
                  {:else}
                    <p>This instance did not expose a runtime noVNC URL.</p>
                  {/if}
                  <p>Operator takeover links must come from the browser runtime, not the dashboard client.</p>
                </div>
              </div>
            {/if}
          </div>
        {:else}
          <div class="flex items-center justify-center min-h-[28rem] rounded-md border border-rule border-dashed bg-paper-warm">
            <div class="text-center text-sm text-ink-mute space-y-2 px-8">
              <div class="w-12 h-12 mx-auto rounded-md bg-paper-soft border border-rule flex items-center justify-center" aria-hidden="true">
                <svg class="w-6 h-6 text-ink-mute" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
              </div>
              <p class="font-medium text-ink">No instance selected</p>
              <p>Click a row in the Instances table to open the xterm log pane and noVNC viewer.</p>
            </div>
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>
