<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { api, listOf } from '$lib/api/client';
  import ErrorPanel from '$lib/components/ErrorPanel.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import DeniedPanel from '$lib/components/DeniedPanel.svelte';
  import StatusBadge from '$lib/components/StatusBadge.svelte';
  import LiveBrowser from '$lib/components/LiveBrowser.svelte';
  import type {
    BrowserInstance,
    BrowserContext,
    BrowserTab,
    BrowserSummary,
  } from '$lib/api/types';

  let summary = $state<BrowserSummary | null>(null);
  let instances = $state<BrowserInstance[]>([]);
  let contexts = $state<BrowserContext[]>([]);
  let tabs = $state<BrowserTab[]>([]);

  let loading = $state(true);
  let denied = $state(false);
  let error = $state<string | null>(null);

  let selectedInstance = $state<BrowserInstance | null>(null);

  let terminalEl = $state<HTMLElement | null>(null);
  let term: { writeln: (s: string) => void; dispose: () => void } | null = null;
  let termReady = $state(false);

  let instanceContexts = $derived(
    selectedInstance
      ? contexts.filter((c) => c.instance_id === instanceId(selectedInstance!))
      : []
  );

  let instanceTabs = $derived(
    selectedInstance
      ? tabs.filter((t) => instanceContexts.some((c) => contextId(c) === t.context_id))
      : []
  );

  // noVNC URLs must be runtime-generated by the gateway/worker and loopback-scoped.
  let noVncSrc = $derived.by(() => {
    const value = selectedInstance?.novnc_url;
    return isLoopbackHttpUrl(value) ? value! : null;
  });

  let rejectedNoVnc = $derived(Boolean(selectedInstance?.novnc_url && !noVncSrc));

  async function load() {
    loading = true;
    error = null;
    denied = false;

    const [sumRes, instRes, ctxRes, tabRes] = await Promise.all([
      api.get('/v1/browser/summary'),
      api.get('/v1/browser/instances'),
      api.get('/v1/browser/contexts'),
      api.get('/v1/browser/tabs'),
    ]);

    loading = false;

    if (instRes.denied) { denied = true; return; }
    if (instRes.error) { error = instRes.error; return; }

    summary = (sumRes.data as BrowserSummary | null) ?? null;
    instances = listOf<BrowserInstance>(instRes);
    contexts = listOf<BrowserContext>(ctxRes);
    tabs = listOf<BrowserTab>(tabRes);
  }

  async function initTerminal() {
    if (!terminalEl || termReady) return;
    try {
      const { Terminal } = await import('@xterm/xterm');
      await import('@xterm/xterm/css/xterm.css');
      term = new Terminal({
        theme: { background: '#111418', foreground: '#d4d4d8' },
        fontFamily: '"Cascadia Mono", "Fira Code", monospace',
        fontSize: 12,
        rows: 20,
        cols: 90,
        cursorBlink: true,
      });
      (term as unknown as { open: (el: HTMLElement) => void }).open(terminalEl);
      writeWelcome();
      termReady = true;
    } catch (e) {
      console.warn('xterm init failed', e);
    }
  }

  function writeWelcome() {
    if (!term) return;
    term.writeln('UBAG Browser Session Log');
    term.writeln('--------------------------------------------------------------------------------');
    if (selectedInstance) {
      term.writeln(`Instance:  ${instanceId(selectedInstance)}`);
      term.writeln(`Status:    ${instanceState(selectedInstance)}`);
      term.writeln(`Contexts:  ${selectedInstance.context_count ?? 0}`);
      term.writeln('--------------------------------------------------------------------------------');
      term.writeln('Live log streaming requires a direct WebSocket connection to the gateway.');
      term.writeln('Use the gateway browser stream endpoint for this instance.');
    } else {
      term.writeln('Select an instance row to view its log stream.');
    }
  }

  function refreshTerminal() {
    if (!term) return;
    (term as unknown as { clear: () => void }).clear?.();
    writeWelcome();
  }

  function selectInstance(inst: BrowserInstance) {
    selectedInstance = inst;
    if (termReady) refreshTerminal();
  }

  function instanceId(inst: BrowserInstance): string {
    return inst.instance_id ?? inst.id ?? '';
  }

  function instanceState(inst: BrowserInstance): string {
    return inst.state ?? inst.status ?? 'unknown';
  }

  function contextId(ctx: BrowserContext): string {
    return ctx.context_id ?? ctx.id ?? '';
  }

  function tabId(tab: BrowserTab): string {
    return tab.tab_id ?? tab.id ?? '';
  }

  function tabState(tab: BrowserTab): string {
    return tab.state ?? tab.status ?? 'unknown';
  }

  function isLoopbackHttpUrl(value?: string | null): boolean {
    if (!value) return false;
    try {
      const url = new URL(value);
      const host = url.hostname.toLowerCase();
      return (
        url.protocol === 'http:' &&
        (host === 'localhost' || host === '127.0.0.1' || host.startsWith('127.') || host === '[::1]' || host === '::1')
      );
    } catch {
      return false;
    }
  }

  function truncate(s: string | undefined | null, n: number): string {
    if (!s) return '-';
    return s.length > n ? s.slice(0, n) + '...' : s;
  }

  onMount(() => {
    load();
  });

  $effect(() => {
    if (terminalEl && !termReady) {
      initTerminal();
    }
  });

  $effect(() => {
    if (selectedInstance && termReady) {
      refreshTerminal();
    }
  });

  onDestroy(() => {
    term?.dispose();
  });
</script>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-display font-bold text-ink">Browser Sessions</h1>
      <p class="text-xs text-ink-mute mt-0.5">Live Chromium automation via UBAG gateway</p>
    </div>
    <button onclick={() => load()} class="text-sm text-accent-deep hover:underline">Refresh</button>
  </div>

  {#if loading}
    <div class="text-ink-mute text-sm animate-pulse">Loading...</div>
  {:else if denied}
    <DeniedPanel resource="browser sessions" />
  {:else if error}
    <ErrorPanel message={error} retry={load} />
  {:else}
    {#if summary}
      <div class="grid grid-cols-3 gap-4">
        {#each [
          { label: 'Instances', value: summary.total_instances ?? summary.instances ?? 0, color: 'text-marine' },
          { label: 'Contexts', value: summary.total_contexts ?? summary.contexts ?? 0, color: 'text-saffron' },
          { label: 'Tabs', value: summary.total_tabs ?? summary.tabs ?? 0, color: 'text-success' },
        ] as card}
          <div class="rounded-md border border-rule bg-paper-soft px-4 py-3 flex flex-col gap-1">
            <span class="text-xs text-ink-mute uppercase tracking-wider font-mono">{card.label}</span>
            <span class="text-2xl font-display font-bold {card.color}">{card.value}</span>
          </div>
        {/each}
      </div>
    {/if}

    <!-- Live interactive browser: stream the real Chrome into the dashboard and
         drive it (log into providers) without a separate window. -->
    <div class="space-y-2">
      <div class="flex items-center justify-between">
        <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Live Browser</h2>
        <span class="text-xs text-ink-mute">Log into a provider here; the session is remembered.</span>
      </div>
      <LiveBrowser />
    </div>

    <div class="grid grid-cols-1 xl:grid-cols-2 gap-6">
      <div class="space-y-3">
        <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Instances</h2>
        {#if instances.length === 0}
          <EmptyState message="No browser instances." hint="Start a browser session via the gateway." />
        {:else}
          <div class="rounded-md border border-rule overflow-x-auto">
            <table class="w-full text-sm">
              <thead class="bg-paper-soft border-b border-rule">
                <tr>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Instance ID</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Status</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Contexts</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each instances as inst, i (instanceId(inst) || i)}
                  <tr
                    role="option"
                    tabindex="0"
                    aria-label="Select instance {instanceId(inst)}"
                    aria-selected={selectedInstance ? instanceId(selectedInstance) === instanceId(inst) : false}
                    class="cursor-pointer transition-colors"
                    class:bg-accent-soft={selectedInstance ? instanceId(selectedInstance) === instanceId(inst) : false}
                    class:hover:bg-paper-soft={selectedInstance ? instanceId(selectedInstance) !== instanceId(inst) : true}
                    onclick={() => selectInstance(inst)}
                    onkeydown={(e) => e.key === 'Enter' && selectInstance(inst)}
                  >
                    <td class="px-4 py-2.5 font-mono text-xs text-ink-mute">{truncate(instanceId(inst), 12)}</td>
                    <td class="px-4 py-2.5"><StatusBadge status={instanceState(inst)} /></td>
                    <td class="px-4 py-2.5 text-ink-soft text-center">{inst.context_count ?? 0}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if contexts.length > 0}
          <h2 class="text-sm font-semibold text-ink uppercase tracking-wider pt-2">Contexts</h2>
          <div class="rounded-md border border-rule overflow-x-auto">
            <table class="w-full text-sm">
              <thead class="bg-paper-soft border-b border-rule">
                <tr>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Context ID</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Instance</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Tabs</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each contexts as ctx, i (contextId(ctx) || i)}
                  <tr class="hover:bg-paper-soft transition-colors">
                    <td class="px-4 py-2.5 font-mono text-xs text-ink-mute">{truncate(contextId(ctx), 12)}</td>
                    <td class="px-4 py-2.5 font-mono text-xs text-ink-soft">{truncate(ctx.instance_id, 8)}</td>
                    <td class="px-4 py-2.5 text-ink-soft text-center">{ctx.tab_count ?? 0}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if tabs.length > 0}
          <h2 class="text-sm font-semibold text-ink uppercase tracking-wider pt-2">Tabs</h2>
          <div class="rounded-md border border-rule overflow-x-auto">
            <table class="w-full text-sm">
              <thead class="bg-paper-soft border-b border-rule">
                <tr>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Tab ID</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Context</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">URL</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Title</th>
                  <th class="px-4 py-2.5 text-left font-medium text-ink-mute text-xs uppercase tracking-wider">Status</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-rule">
                {#each tabs as tab, i (tabId(tab) || i)}
                  <tr class="hover:bg-paper-soft transition-colors">
                    <td class="px-4 py-2.5 font-mono text-xs text-ink-mute">{truncate(tabId(tab), 8)}</td>
                    <td class="px-4 py-2.5 font-mono text-xs text-ink-mute">{truncate(tab.context_id, 8)}</td>
                    <td class="px-4 py-2.5 text-xs text-ink-soft max-w-[12rem] truncate" title={tab.url ?? ''}>{truncate(tab.url, 40)}</td>
                    <td class="px-4 py-2.5 text-xs text-ink max-w-[10rem] truncate" title={tab.title ?? ''}>{truncate(tab.title, 30)}</td>
                    <td class="px-4 py-2.5"><StatusBadge status={tabState(tab)} /></td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}

        {#if instances.length === 0 && contexts.length === 0 && tabs.length === 0}
          <EmptyState message="No browser sessions active." hint="Browser instances, contexts, and tabs will appear here." />
        {/if}
      </div>

      <div class="space-y-4">
        {#if selectedInstance}
          <div class="flex items-center justify-between">
            <div>
              <h2 class="text-sm font-semibold text-ink uppercase tracking-wider">Session Viewer</h2>
              <p class="text-xs font-mono text-ink-mute mt-0.5">{instanceId(selectedInstance)}</p>
            </div>
            <StatusBadge status={instanceState(selectedInstance)} />
          </div>

          <div class="space-y-1.5">
            <div class="flex items-center justify-between">
              <span class="text-xs font-mono text-ink-mute uppercase tracking-wider">Log Stream</span>
              <span class="text-xs text-ink-mute italic">WebSocket connection required for live data</span>
            </div>
            <div
              bind:this={terminalEl}
              class="w-full rounded-md overflow-hidden border border-rule"
              style="min-height: 180px;"
              aria-label="Terminal log pane for instance {instanceId(selectedInstance)}"
            ></div>
          </div>

          {#if instanceContexts.length > 0}
            <div class="rounded-md border border-rule bg-paper-soft px-4 py-3 text-xs space-y-1">
              <p class="font-mono text-ink-mute uppercase tracking-wider mb-2">Instance Contexts</p>
              {#each instanceContexts as ctx}
                <div class="flex items-center gap-4">
                  <span class="font-mono text-ink">{truncate(contextId(ctx), 12)}</span>
                  <span class="text-ink-mute">{ctx.tab_count ?? 0} tab{ctx.tab_count !== 1 ? 's' : ''}</span>
                </div>
              {/each}
            </div>
          {/if}

          {#if instanceTabs.length > 0}
            <div class="rounded-md border border-rule bg-paper-soft px-4 py-3 text-xs space-y-1">
              <p class="font-mono text-ink-mute uppercase tracking-wider mb-2">Instance Tabs</p>
              {#each instanceTabs as tab}
                <div class="flex items-center gap-3">
                  <span class="font-mono text-ink-mute">{truncate(tabId(tab), 8)}</span>
                  <span class="text-ink truncate max-w-[20rem]" title={tab.url ?? ''}>{truncate(tab.url, 50)}</span>
                  <StatusBadge status={tabState(tab)} />
                </div>
              {/each}
            </div>
          {/if}

          <div class="space-y-1.5">
            <div class="flex items-center justify-between">
              <span class="text-xs font-mono text-ink-mute uppercase tracking-wider">noVNC Viewer</span>
              <span class="text-xs text-ink-mute italic">Requires a runtime-generated loopback URL</span>
            </div>
            {#if noVncSrc}
              <iframe
                src={noVncSrc}
                class="w-full rounded-md border border-rule bg-paper-warm"
                style="height: 20rem;"
                title="noVNC Viewer - {instanceId(selectedInstance)}"
                sandbox="allow-same-origin allow-scripts allow-forms"
                aria-label="noVNC remote desktop viewer for instance {instanceId(selectedInstance)}"
              ></iframe>
            {:else}
              <div class="flex items-center justify-center rounded-md border border-rule bg-paper-warm" style="height: 20rem;">
                <div class="text-center text-xs text-ink-mute space-y-1">
                  <p class="font-medium text-ink">noVNC unavailable</p>
                  {#if rejectedNoVnc}
                    <p>The gateway returned a non-loopback noVNC URL, so it was not embedded.</p>
                  {:else}
                    <p>This instance did not expose a runtime noVNC URL.</p>
                  {/if}
                  <p>Operator takeover links must come from the browser runtime, not the dashboard client.</p>
                </div>
              </div>
            {/if}
          </div>
        {:else}
          <div class="flex items-center justify-center rounded-md border border-rule border-dashed bg-paper-warm" style="min-height: 28rem;">
            <div class="text-center text-sm text-ink-mute space-y-2 px-8">
              <div class="w-12 h-12 mx-auto rounded-md bg-paper-soft border border-rule flex items-center justify-center" aria-hidden="true">
                <svg class="w-6 h-6 text-ink-mute" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
              </div>
              <p class="font-medium text-ink">No instance selected</p>
              <p>Click a row in the Instances table to open the xterm log pane and noVNC viewer.</p>
            </div>
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>
