;; echo_transform.wat - WAT source for the echo_transform.wasm fixture
;;
;; This module implements the ubag plugin v1 JSON ABI for tests:
;;   - alloc(size i32) -> i32   — always returns 0 (allocates at address 0)
;;   - transform(ptr i32, len i32) -> i64  — echoes input by returning packed (ptr<<32)|len
;;
;; The "echo" semantics work because the host wrote the input JSON at address 0
;; (ptr=0 from alloc), and the transform returns (0<<32)|len, so the host reads
;; back the same bytes it wrote — a zero-copy identity round-trip.
;;
;; Build: wat2wasm echo_transform.wat -o echo_transform.wasm
;;
;; Note: The committed echo_transform.wasm was generated by gen_wasm_main.go
;; (go run gen_wasm_main.go from this directory), which embeds the binary
;; directly as Go byte literals.  The .wat here is the canonical readable source.

(module
  ;; One page of linear memory (64 KiB), exported for host access.
  (memory (export "memory") 1)

  ;; alloc(size i32) -> i32
  ;; Always returns 0: allocates at the start of linear memory.
  ;; The host writes inputJSON there before calling transform.
  (func (export "alloc") (param $size i32) (result i32)
    i32.const 0
  )

  ;; transform(ptr i32, len i32) -> i64
  ;; Returns the packed u64 (ptr<<32)|len, which points back to the input.
  ;; The host reads resultLen bytes from resultPtr — i.e. the original input bytes.
  (func (export "transform") (param $ptr i32) (param $len i32) (result i64)
    local.get $ptr
    i64.extend_i32_u
    i64.const 32
    i64.shl
    local.get $len
    i64.extend_i32_u
    i64.or
  )
)
